@startuml
package "hcm" {
    class "staff" {
        *id: BIGINT
        *created_at: DATETIME
        *updated_at: DATETIME
        *first_name: VARCHAR
        *last_name: VARCHAR
        *phone_number: VARCHAR
        *person_profile_id: BIGINT
        *nursing_home_id: BIGINT
    }

    class "contracts" {
        *id: BIGINT
        *created_at: DATETIME
        *updated_at: DATETIME
        *start_date: DATE
        *end_date: DATE
        *contract_status: ENUM
        *staff_role: ENUM
        *type_of_contract: VARCHAR
        *work_shift: ENUM
        *staff_id: BIGINT
    }
}

staff "1" -- "0.*" contracts

@enduml