# Environment: Production
environment.name=prod

# Spring DataSource Configuration
spring.datasource.url=jdbc:mysql://${DATABASE_URL}:${DATABASE_PORT}/${DATABASE_SCHEMA}?useSSL=false&serverTimezone=UTC
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
## MongoDB
spring.data.mongodb.uri=mongodb://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
spring.data.mongodb.database=${DATABASE_NAME}
# JWT Configuration
authorization.jwt.secret=${AUTHORIZATION_JWT_SECRET}
authorization.jwt.expiration.days=${AUTHORIZATION_JWT_EXPIRATION_DAYS:7}

# Stripe Configuration Properties
stripe.api.key=${STRIPE_API_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

# Cloudinary Configuration Properties
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
# Spring Data JPA Configuration
spring.jpa.show-sql=false
